### ISSUE TITLE
Ubuntu build

### ISSUE THREAD

**Issue by f8ttyc8t** [ncgrep/ncgrep#2]
Hi,
I found event it builds pretty well under Mac, it fails under Ubuntu.

For me using additional compiler/linker switches in `build.sh` helps:

```
#!/bin/bash

g++ -c -std=c++0x files.cpp -o files.o
g++ -c -std=c++0x grep.cpp -o grep.o
g++ -c -std=c++0x tui.cpp -o tui.o
g++ -c -std=c++0x data.cpp -o data.o
g++ -g -std=c++0x -pthread main.cpp -o ncgrep files.o grep.o tui.o data.o -lncurses
./ncgrep string . 3
```

**Comment by huxiaoxu2019** [comment]
Thanks, I think I should provide the Makefile for compiling the software later.

**Comment by f8ttyc8t** [comment]
Because I've troubles using git I've attached a [makefile](https://github.com/ncgrep/ncgrep/files/1539773/makefile.txt) to do so...

**Comment by huxiaoxu2019** [comment]
What's the trouble using git?

**Comment by f8ttyc8t** [comment]
Nothing wrong with git itself, I'm just not pro enough to add a makefile to existing repository without creating a new fork.

**Comment by f8ttyc8t** [comment]
Sorry, pressed "Close and comment" before.

**Comment by huxiaoxu2019** [comment]
May it's because that I just change the git repository author info which is wrong, so you should have to create the new fork. [https://help.github.com/articles/changing-author-info/](https://help.github.com/articles/changing-author-info/)

**Comment by f8ttyc8t** [comment]
Thanks, that explains it.

**Comment by huxiaoxu2019** [comment]
Thanks for your pr: [https://github.com/ncgrep/ncgrep/pull/3](https://github.com/ncgrep/ncgrep/pull/3)
